pipeline {
    agent any

    parameters {
        booleanParam(name: 'PLAN_TERRAFORM', defaultValue: false, description: 'Check to plan Terraform changes')
        booleanParam(name: 'APPLY_TERRAFORM', defaultValue: false, description: 'Check to apply Terraform changes')
        booleanParam(name: 'DESTROY_TERRAFORM', defaultValue: false, description: 'Check to destroy Terraform infrastructure')
    }

    tools {
        terraform 'terraform'  // Terraform tool configured in Jenkins
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Clean workspace and clone the Git repository
                deleteDir()
                git branch: 'main',
                    url: 'https://github.com/DevinLiggins14/Terraform-Jenkins-AWS-REST-API-Deployment.git'
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials-demo-user']]) {
                    dir("${WORKSPACE}/worker_scripts/app_infrastructure") {
                        sh 'echo "================= Terraform Init =================="'
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Plan') {
            when {
                expression { params.PLAN_TERRAFORM }
            }
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials-demo-user']]) {
                    dir("${WORKSPACE}/worker_scripts/app_infrastructure") {
                        sh 'echo "================= Terraform Plan =================="'
                        sh 'terraform plan'
                    }
                }
            }
        }

        stage('Terraform Apply') {
            when {
                expression { params.APPLY_TERRAFORM }
            }
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials-demo-user']]) {
                    dir("${WORKSPACE}/worker_scripts/app_infrastructure") {
                        sh 'echo "================= Terraform Apply =================="'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

        stage('Terraform Destroy') {
            when {
                expression { params.DESTROY_TERRAFORM }
            }
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials-demo-user']]) {
                    dir("${WORKSPACE}/worker_scripts/app_infrastructure") {
                        sh 'echo "================= Terraform Destroy =================="'
                        sh 'terraform destroy -auto-approve'
                    }
                }
            }
        }
    }
}
